CREATE TABLE tbl_khach_hang(
    id INTEGER GENERATED BY DEFAULT ON NULL  AS IDENTITY PRIMARY KEY,
    ho VARCHAR2(64) NOT NULL,
    ten VARCHAR2(64) NOT NULL,
    gioi_tinh NUMBER(1) DEFAULT 1,
    ngay_sinh DATE CONSTRAINT ngay_sinh_check 
    CHECK (ngay_sinh >= TO_DATE('1930-01-01', 'YYYY-MM-DD')),
    dien_thoai VARCHAR2(11) NOT NULL UNIQUE,
    dia_chi VARCHAR2(128),
    email VARCHAR2(128) NOT NULL UNIQUE,
    ngay_tao DATE DEFAULT SYSDATE,
    ngay_cap_nhat DATE,
    trang_thai NUMBER(1) DEFAULT 1
);
COMMIT;
CREATE OR REPLACE TRIGGER CheckNgayCapNhat
BEFORE INSERT OR UPDATE ON tbl_khach_hang
FOR EACH ROW
BEGIN
    IF :NEW.ngay_cap_nhat > SYSDATE THEN
        RAISE_APPLICATION_ERROR(-20000, 'Ngày c?p nh?t không ???c l?n h?n ngày hi?n t?i');
--    END IF;
END;

COMMIT;

INSERT INTO tbl_khach_hang (ho, ten, gioi_tinh, ngay_sinh, dien_thoai, dia_chi, email)
VALUES ('Nguyen', 'Van Thành', 1, TO_DATE('1990-05-15', 'YYYY-MM-DD'), '0123456789', '123 ?ình Thôn', 'nguyenvana@email.com');
INSERT INTO tbl_khach_hang (ho, ten, gioi_tinh, ngay_sinh, dien_thoai, dia_chi, email)
VALUES ('Tran', 'Thi M?', 0, TO_DATE('1985-12-20', 'YYYY-MM-DD'), '9876543210', '45 ???ng G?i Phóng', 'tranthib@email.com');
INSERT INTO tbl_khach_hang (ho, ten, gioi_tinh, ngay_sinh, dien_thoai, dia_chi, email)
VALUES ('Le', 'Duc M?nh', 1, TO_DATE('1988-08-10', 'YYYY-MM-DD'), '0999888777', '74 C?u Gi?y', 'leducc@email.com');
commit;
DROP TRIGGER CheckNgayCapNhat;
SELECT * FROM TBL_KHACH_HANG;
DROP TABLE TBL_KHACH_HANG;
CREATE TABLE tbl_diem_thuong(
         id INTEGER GENERATED BY DEFAULT ON NULL  AS IDENTITY PRIMARY KEY,
        id_khach_hang INTEGER ,
        noi_dung VARCHAR2(128),
        diem SMALLINT ,
        ngay_tao DATE DEFAULT SYSDATE,
    FOREIGN KEY (id_khach_hang) REFERENCES tbl_khach_hang(id)
);
COMMIT;
-- Insert d? li?u vào b?ng tbl_diem_thuong
INSERT INTO tbl_diem_thuong (id_khach_hang, noi_dung, diem)
VALUES  (1, 'Mua hàng tháng 5', 10);
    INSERT INTO tbl_diem_thuong (id_khach_hang, noi_dung, diem)
VALUES (2, '??ng ký thành viên', 5);
    INSERT INTO tbl_diem_thuong (id_khach_hang, noi_dung, diem)
VALUES (43, 'L??t mua s?m tháng 11', 8);
    INSERT INTO tbl_diem_thuong (id_khach_hang, noi_dung, diem)
VALUES (39, 'L??t mua s?m tháng 9', 15);

COMMIT;

SELECT * FROM TBL_DIEM_THUONG;
DROP TABLE TBL_DIEM_THUONG;
COMMIT;
    

CREATE TABLE tbl_cua_hang(
     id INTEGER GENERATED BY DEFAULT ON NULL  AS IDENTITY PRIMARY KEY,
    ten_cua_hang VARCHAR2(128) NOT NULL,
    dia_chi VARCHAR2(128) NOT NULL,
    sdt1 VARCHAR2(11) NOT NULL UNIQUE,
    sdt2 VARCHAR2(11),
    id_nhan_vien INTEGER,
    gio_mo_cua NUMBER(3) CONSTRAINT check_gio_mo_cua
    CHECK (gio_mo_cua >=0 AND gio_mo_cua <= 255) ,
     gio_dong_cua NUMBER(3) CONSTRAINT check_gio_dong_cua
    CHECK (gio_dong_cua >=0 AND gio_dong_cua <= 255) ,
    ghi_chu VARCHAR2(256),
FOREIGN KEY (id_nhan_vien) REFERENCES tbl_nhan_vien(id)

);
COMMIT;
INSERT INTO tbl_cua_hang (ten_cua_hang, dia_chi, sdt1, sdt2, id_nhan_vien, gio_mo_cua, gio_dong_cua, ghi_chu)
VALUES
('C?a hàng Vinmat Hà ?ông', '??a ch? 78 Khu?t Duy Ti?n', '1234567890', '0987654321', 1, 8, 18, 'C?a hàng r?t ?ông');
INSERT INTO tbl_cua_hang (ten_cua_hang, dia_chi, sdt1, sdt2, id_nhan_vien, gio_mo_cua, gio_dong_cua, ghi_chu)
VALUES
('C?a hàng Vinmat Nam ??nh', '??a ch? 20 Gi?i Phóng', '9876543210', NULL, 2, 9, 19, 'C?a hàng r?t ?ông');
INSERT INTO tbl_cua_hang (ten_cua_hang, dia_chi, sdt1, sdt2, id_nhan_vien, gio_mo_cua, gio_dong_cua, ghi_chu)
VALUES
('C?a hàng Vinmat C?u Gi?y', '??a ch? 104 Ph?m V?n ??ng ', '1112223333', '4445556666', 3, 10, 20, 'C?a hàng r?t ?ông');
commit;
SELECT * FROM TBL_CUA_HANG;
DROP TABLE tbl_cua_hang;

CREATE TABLE tbl_phan_quyen(
   id INTEGER GENERATED BY DEFAULT ON NULL  AS IDENTITY PRIMARY KEY,
     ten_quyen VARCHAR2(64) NOT NULL,
    vi_tri VARCHAR2(64)  NOT NULL,
     ngay_tao DATE DEFAULT SYSDATE,
    ghi_chu VARCHAR2(256)
);
COMMIT;
-- Thêm 3 dòng d? li?u cho b?ng tbl_phan_quyen
INSERT INTO tbl_phan_quyen (id,ten_quyen, vi_tri, ghi_chu)
VALUES (1,'Manage', 'Qu?n tr? viên', 'Phân quy?n cao nh?t');

INSERT INTO tbl_phan_quyen (id,ten_quyen, vi_tri, ghi_chu)
VALUES (2,'Nhân Viên', 'Nhân viên bán hàng', 'Phân quy?n cho nhân viên bán hàng');


COMMIT;
DELETE FROM tbl_phan_quyen;
DROP TABLE  tbl_phan_quyen;

select *from tbl_phan_quyen;





CREATE TABLE tbl_nhan_vien(
     id INTEGER GENERATED BY DEFAULT ON NULL  
     AS IDENTITY PRIMARY KEY, 
    ho_va_ten VARCHAR2(64) NOT NULL,
    gioi_tinh NUMBER(1) DEFAULT 1,
    ngay_sinh DATE NOT NULL,
    ngay_vao_lam DATE DEFAULT SYSDATE,
    di_dong VARCHAR2(11) NOT NULL UNIQUE,
    dt_gia_dinh VARCHAR2(11),
    email VARCHAR2(128)UNIQUE,
    dia_chi VARCHAR2(128),
    id_phan_quyen INTEGER NOT NULL ,
    username VARCHAR2(64),
    passwords VARCHAR2(64), 
    luong_co_ban FLOAT DEFAULT 0,    
    ghi_chu VARCHAR2(256),
    trang_thai NUMBER(1) DEFAULT 1,
    FOREIGN KEY (id_phan_quyen) REFERENCES tbl_phan_quyen(id)
   

);
COMMIT;
INSERT INTO tbl_nhan_vien (ho_va_ten, gioi_tinh, ngay_sinh, ngay_vao_lam, di_dong, dt_gia_dinh, email, dia_chi, id_phan_quyen, luong_co_ban, username, passwords, ghi_chu, trang_thai)
VALUES ('Nguyen Van A', 1, TO_DATE('2004-03-26', 'yyyy-MM-dd'), TO_DATE('2023-02-27', 'yyyy-MM-dd'), '0123456789', '0987654321', 'nguyenvana@gmail.com', '123 Nguyen Du, TP.HCM', 1, 5000000, 'nguyenvana', 'hashed_password', 'Ghi chú v?  A', 1);

INSERT INTO tbl_nhan_vien (ho_va_ten, gioi_tinh, ngay_sinh, ngay_vao_lam, di_dong, dt_gia_dinh, email, dia_chi, id_phan_quyen, luong_co_ban, username, passwords, ghi_chu, trang_thai)
VALUES ('Tran Thi B', 0,  TO_DATE('2006-02-27', 'yyyy-MM-dd'), TO_DATE('2023-02-9', 'yyyy-MM-dd'), '0987654321', '0123456789', 'tranthib@gmail.com', '456 Le Loi, TP.HCM', 2, 5500000, 'tranthib', 'hashed_password2', 'Ghi chú v? nhân viên B', 1);

INSERT INTO tbl_nhan_vien (ho_va_ten, gioi_tinh, ngay_sinh, ngay_vao_lam, di_dong, dt_gia_dinh, email, dia_chi, id_phan_quyen, luong_co_ban, username, passwords, ghi_chu, trang_thai)
VALUES ('Tran Thi H', 0,  TO_DATE('2006-02-28', 'yyyy-MM-dd'), TO_DATE('2023-02-7', 'yyyy-MM-dd'), '0987654891', '0123450989', 'tranthih@gmail.com', '45 Le Loi, TP.HCM', 2, 5900000, 'tranthih', 'hashed_password4', 'Ghi chú v? nhân viên h', 1);
INSERT INTO tbl_nhan_vien (ho_va_ten, gioi_tinh, ngay_sinh, ngay_vao_lam, di_dong, dt_gia_dinh, email, dia_chi, id_phan_quyen, luong_co_ban, username, passwords, ghi_chu, trang_thai)
VALUES ('Nguyen Van KH', 1, TO_DATE('2004-04-29', 'yyyy-MM-dd'), TO_DATE('2023-04-28', 'yyyy-MM-dd'), '0123433789', '0987754321', 'nguyenvakha@gmail.com', '123 Nguyen Du, TP.HCM', 1, 5400000, 'nguyenvankhs', 'hashed_password', 'Ghi chú v?  KH', 1);

COMMIT;
DROP TABLE tbl_nhan_vien;
SELECT * FROM tbl_nhan_vien;

CREATE TABLE tbl_chung_loai(
    id INTEGER GENERATED BY DEFAULT ON NULL  
    AS IDENTITY PRIMARY KEY, 
    ten VARCHAR2(64)NOT NULL,
    mo_ta VARCHAR2(128),
    ngay_tao DATE ,
    ngay_cap_nhat DATE,
    trang_thai NUMBER(1) DEFAULT 1
);
COMMIT;

INSERT INTO tbl_chung_loai (ten, mo_ta, ngay_tao)
VALUES ('Cà phê ?en', 'Cà phê ?en ??m ?à', SYSDATE);
INSERT INTO tbl_chung_loai (ten, mo_ta, ngay_tao)
VALUES ('Cà phê s?a', 'Cà phê s?a', SYSDATE);
INSERT INTO tbl_chung_loai (ten, mo_ta, ngay_tao)
VALUES ('Matcha ?á say', 'Matcha trà xanh ??n t? Nh?t B?n', SYSDATE);
INSERT INTO tbl_chung_loai (ten, mo_ta, ngay_tao)
VALUES ('H?ng trà trân châu', 'H?ng trà ??n t?  H?ng Kông', SYSDATE);
INSERT INTO tbl_chung_loai (ten, mo_ta, ngay_tao)
VALUES ('Cafe phân ch?n', 'Ch?n t? thiên nhiên', SYSDATE);
commit;
DROP TABLE  tbl_chung_loai;

CREATE TABLE tbl_don_vi_tinh(
    id INTEGER GENERATED BY DEFAULT ON NULL  
    AS IDENTITY PRIMARY KEY, 
    ten_don_vi VARCHAR(32) NOT NULL,
    ghi_chu VARCHAR2(256)

);

COMMIT;
-- Chèn ??n v? tính 1
INSERT INTO tbl_don_vi_tinh (ten_don_vi, ghi_chu)
VALUES ('1 Dessertspoon', 'th? tích b?ng hai mu?ng cà phê ho?c 10 ml. ');

-- Chèn ??n v? tính 2
INSERT INTO tbl_don_vi_tinh (ten_don_vi, ghi_chu)
VALUES ('1 Fluid ounce', 'kho?ng 30 ml');
INSERT INTO tbl_don_vi_tinh (ten_don_vi, ghi_chu)
VALUES ('1 cup', 'khoang 178ml');
INSERT INTO tbl_don_vi_tinh (ten_don_vi, ghi_chu)
VALUES ('1 pound', '473,17 ml trong th? tích.');


COMMIT;
DROP TABLE  tbl_don_vi_tinh;

CREATE TABLE tbl_nha_cung_cap(
     id INTEGER GENERATED BY DEFAULT ON NULL  
    AS IDENTITY PRIMARY KEY, 
    ten_nhacc VARCHAR2(128) NOT NULL,
    dia_chi VARCHAR2(256) NOT NULL,
    sdt1 VARCHAR2(24) NOT NULL,
    sdt2 VARCHAR2(24),
    fax VARCHAR2(16),
    email VARCHAR2(256) NOT NULL UNIQUE,
    website VARCHAR2(256) NOT NULL UNIQUE,
    gay_tao DATE DEFAULT SYSDATE,
    ngay_cap_nhat DATE,
    tax_code VARCHAR2(64),
    ghi_chu VARCHAR2(512),
    trang_thai NUMBER(1) DEFAULT 1
 
);
COMMIT;
-- Chèn d? li?u cho Nhà cung c?p 1
INSERT INTO tbl_nha_cung_cap (ten_nhacc, dia_chi, sdt1, sdt2, fax, email, website, tax_code, ghi_chu)
VALUES
  ('Drai Farm – Cà Phê T? Nông Tr?i ', 'Thôn Hi?p Bình, xã Qu?ng Hi?p, huy?n C? M gar t?nh DakLak', '0946 803 447', '0946 803 558', '1234', 'draifarm.cafe@gmail.com', 'https://draifarm.com/', '12345', 'Cà phê Drai Farm – Cà Phê T? Nông Tr?i tr?c ti?p s?n xu?t t? chính nông tr?i c?a mình và liên k?t v?i các nông h? t?i huy?n C? M’gar, DakLak');

-- Chèn d? li?u cho Nhà cung c?p 2
INSERT INTO tbl_nha_cung_cap (ten_nhacc, dia_chi, sdt1, sdt2, fax, email, website, tax_code, ghi_chu)
VALUES
  ('Ch?n Vàng Coffee', 'S? 3, ?p 1, Xã Tân B?u, Huy?n B?n L?c, T?nh Long An', '0907 330 011','0907 330 022', '5678', 'admin@hucafood.com', 'https://sieuthicafe.com/product-category/brand/golden-weasel-coffee/', '54321', 'T?i ?ây th?c s? có th? ??m b?o cà phê s?ch t? nông tr??ng cho ??n t?ng ly cà phê c?a khách hàng');

-- Chèn d? li?u cho Nhà cung c?p 3
INSERT INTO tbl_nha_cung_cap (ten_nhacc, dia_chi, sdt1, sdt2, fax, email, website, tax_code, ghi_chu)
VALUES
  ('Cà phê Tri?u Nguyên', '120A Lý Thái T?, Xã ?amb’ri, TP B?o L?c  t?nh Lâm ??ng  ', '0966 770 770', '0968 770 770', '3333', 'sales@trieunguyencoffee.com ', 'https://caphetrieunguyen.com/', '5801317791', ' Cà phê MOKA C?u ??t, Robusta nguyên ch?t, cà phê nguyên ch?t Blackgoat, culi nguyên ch?t,.. H?p tác cùng Tri?u Nguyên');

-- Chèn d? li?u cho Nhà cung c?p 4
INSERT INTO tbl_nha_cung_cap (ten_nhacc, dia_chi, sdt1, sdt2, fax, email, website, tax_code, ghi_chu)
VALUES
  ('Cà phê Buôn Mê', 'Huy?n C? M’gar – ??k L?k và xã Tr?m Hành ,C?u ??t', '0909 555 301', ' 0918 555 302', '6666', 'buonmecoffee@gmail.com', 'www.rangxaycaphe.com.vn', '88888', ' Cà phê Buôn Mê ???c s?n xu?t theo quy trình khép kín, b?ng công ngh? rang bán-hot-air tiên ti?n k?t h?p b? máy nhi?u t?ng l?c.');

-- Chèn d? li?u cho Nhà cung c?p 5
INSERT INTO tbl_nha_cung_cap (ten_nhacc, dia_chi, sdt1, sdt2, fax, email, website, tax_code, ghi_chu)
VALUES
('Retro Coffee', '02 Nguy?n Ng?c Nh?t, Qu?n Tân Phú, TPHCM', '0911 222 678', '0935 563 679', '9999', 'info@retrocoffee.vn', 'https://retrocoffee.vn/', '77777', 'B? máy máy rang công ngh? Semi Hot Air hi?n ??i ??n t? ??c');
COMMIT;

DROP TABLE  tbl_nha_cung_cap;

CREATE TABLE tbl_hinh_anh(
    id INTEGER PRIMARY KEY,
    id_san_pham INTEGER ,
    ghi_chu VARCHAR2(64),
    stt  NUMBER(3) ,
    trang_thai NUMBER(1) DEFAULT 1,
    FOREIGN KEY (id_san_pham) REFERENCES tbl_hang_hoa(id)
);
COMMIT;
DROP TABLE tbl_hinh_anh;

CREATE TABLE tbl_van_chuyen (
     id INTEGER GENERATED BY DEFAULT ON NULL  
     AS IDENTITY PRIMARY KEY, 
    ten VARCHAR2(64),
    ghi_chu VARCHAR(256),
    trang_thai NUMBER(1) DEFAULT 1
);
COMMIT;
DROP TABLE tbl_van_chuyen;

CREATE TABLE tbl_thanh_toan(
     id INTEGER GENERATED BY DEFAULT ON NULL  
    AS IDENTITY PRIMARY KEY, 
    ten VARCHAR2(64),
    ghi_chu VARCHAR2(128),
    trang_thai NUMBER(1) DEFAULT 1
);
COMMIT;
DROP TABLE tbl_thanh_toan;

CREATE TABLE tbl_hoa_don(
     id INTEGER GENERATED BY DEFAULT ON NULL  
    AS IDENTITY PRIMARY KEY, 
    ngay_tao DATE DEFAULT SYSDATE,
    ngay_giao_hang DATE ,
    
    id_thanh_toan INTEGER,
    id_khach_hang INTEGER NOT NULL,
    id_nhan_vien INTEGER NOT NULL,
    trang_thai  NUMBER(1) DEFAULT 1,
    dia_chi_nhan   VARCHAR2(128),
    sdt_nhan VARCHAR2(11)NOT NULL,
    ghi_chu VARCHAR2(128),
   
    FOREIGN KEY (id_thanh_toan) REFERENCES tbl_thanh_toan(id),
    FOREIGN KEY (id_khach_hang) REFERENCES tbl_khach_hang(id),
    FOREIGN KEY (id_nhan_vien) REFERENCES tbl_nhan_vien(id)
    
    );

CREATE SEQUENCE seq_id_thanh_toan
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE OR REPLACE TRIGGER set_id_thanh_toan
BEFORE INSERT ON tbl_hoa_don
FOR EACH ROW
BEGIN
    IF :NEW.id_thanh_toan IS NULL THEN
        SELECT seq_id_thanh_toan.NEXTVAL INTO :NEW.id_thanh_toan FROM DUAL;
        
        -- C?p nh?t giá tr? id_thanh_toan trong b?ng tbl_thanh_toan
        INSERT INTO tbl_thanh_toan (id) VALUES (:NEW.id_thanh_toan);
    END IF;
END;
/
COMMIT;


 DROP TABLE tbl_hoa_don;
    
CREATE TABLE tbl_hang_hoa(
    id INTEGER GENERATED BY DEFAULT ON NULL  
    AS IDENTITY PRIMARY KEY, 
    bar_code VARCHAR2(32) NOT NULL,
    ten_hang_hoa VARCHAR2(128) NOT NULL,
    id_chung_loai INTEGER ,
    id_don_vi_tinh INTEGER ,
    id_nhacc INTEGER,
    so_luong FLOAT  DEFAULT 0,
    gia_nhap FLOAT  DEFAULT 0,
    gia_xuat FLOAT DEFAULT 0,
    ngay_tao DATE DEFAULT SYSDATE,
    ngay_cap_nhat DATE ,
    ghi_chu VARCHAR2(128),
    FOREIGN KEY (id_chung_loai) REFERENCES tbl_chung_loai(id),
    FOREIGN KEY (id_don_vi_tinh) REFERENCES tbl_don_vi_tinh(id),
    FOREIGN KEY (id_nhacc) REFERENCES tbl_nha_cung_cap(id)
    );    
    COMMIT;

commit;
INSERT INTO tbl_hang_hoa (bar_code, ten_hang_hoa, id_chung_loai, id_don_vi_tinh, id_nhacc, so_luong, gia_nhap, gia_xuat, ghi_chu)
VALUES ('1234567890', 'Cà phê ?en dá', 1, 1, 1, 100, 50000, 100000, 'S?n ph?m ch?t l??ng cao');
INSERT INTO tbl_hang_hoa (bar_code, ten_hang_hoa, id_chung_loai, id_don_vi_tinh, id_nhacc, so_luong, gia_nhap, gia_xuat, ghi_chu)
VALUES ('9876543210', 'Cà phê phân ch?n', 5, 3, 2, 80, 40000, 90000, 'S?n ph?m pha ch? ??c bi?t');
INSERT INTO tbl_hang_hoa (bar_code, ten_hang_hoa, id_chung_loai, id_don_vi_tinh, id_nhacc, so_luong, gia_nhap, gia_xuat, ghi_chu)
VALUES ('4567890123', 'B?c s?u', 2, 4, 5, 60, 10005, 300000, 'Nhi?u s?a ít cafe');
INSERT INTO tbl_hang_hoa (bar_code, ten_hang_hoa, id_chung_loai, id_don_vi_tinh, id_nhacc, so_luong, gia_nhap, gia_xuat, ghi_chu)
VALUES ('9876543210', 'Matcha ?á say', 3, 5, 2, 80, 40000, 90000, 'S?n ph?m pha ch? ??c bi?t');
INSERT INTO tbl_hang_hoa (bar_code, ten_hang_hoa, id_chung_loai, id_don_vi_tinh, id_nhacc, so_luong, gia_nhap, gia_xuat, ghi_chu)
VALUES ('4567890123', 'H?ng trà', 4, 5, 5, 60, 10005, 300000, 'D?m v? trà');

commit;

     DROP TABLE tbl_hang_hoa;
    
    
    CREATE TABLE tbl_hoa_don_chi_tiet(
       so_luong INTEGER,
        gia FLOAT,
        id_hoa_don INTEGER,
        id_hang_hoa INTEGER,
        FOREIGN KEY (id_hoa_don) REFERENCES tbl_hoa_don(id),
        FOREIGN KEY (id_hang_hoa) REFERENCES tbl_hang_hoa(id),
        PRIMARY KEY( id_hoa_don,id_hang_hoa)
    );
    COMMIT;
      DROP TABLE tbl_hoa_don_chi_tiet;
CREATE TABLE tbl_temp_cart(
    id INTEGER GENERATED BY DEFAULT ON NULL  
    AS IDENTITY PRIMARY KEY, 
    id_hang_hoa  INTEGER ,
    so_luong FLOAT,
    gia FLOAT,
    FOREIGN KEY (id_hang_hoa) REFERENCES tbl_hang_hoa(id)
    
    
    );    



COMMIT;
DROP TABLE tbl_temp_cart;
CREATE TABLE tbl_thong_ke (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    ten_hang_hoa VARCHAR2(128),
    so_luong FLOAT,
    doanh_thu FLOAT,
    ngay_thong_ke DATE
);
COMMIT;
